name: CI Pipeline v2

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set image tag
      run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t ib28071969/cicd-demo:${IMAGE_TAG} .

    - name: Push Docker image
      run: docker push ib28071969/cicd-demo:${IMAGE_TAG}

    - name: Tag latest
      run: |
        docker tag ib28071969/cicd-demo:${IMAGE_TAG} ib28071969/cicd-demo:latest
        docker push ib28071969/cicd-demo:latest  
